## CIND830 - Python Programming for Data Science  
### Assignment 2 (10% of the final grade)
### Due on May 31, 2021 11:59 PM

*****
This is a Jupyter Notebook document that extends a simple formatting syntax for authoring HTML and PDF. Review [this](https://jupyter-notebook.readthedocs.io/en/stable/notebook.html) website for more details on using Jupyter Notebooks.

Use the JupyterHub server on the Google Cloud Platform, provided by your designated instructor, for this assignment. Ensure using **Python 3.7.6** release then complete the assignment by inserting your Python code wherever seeing the string `#INSERT YOUR ANSWER HERE.`

When you click the `File` button, from the top navigation bar, then select `Export Notebook to HTML`, an HTML document will be generated that includes both the assignment content and the output of any embedded Python code chunks.

Use [these](https://www.ryerson.ca/courses/students/tutorials/assignments/) guidelines to submit **both** the IPYNB and the exported file (HTML). Failing to submit both files will be subject to mark deduction.

Please be advised that you cannot get more than 100% in this assignment, and the **BONUS** question will only be graded if all other questions have been submitted.

*****

### Question 1 **[50 pts]**:

**a)** **[10 pts]** Define a function called `is_even` that takes an integer as a parameter and returns `True` if the given integer is Even. An integer is said to be even if the modulo(%) of the integer equals `0`. For example, `4` is even `(4%2 = 0)`, but `5` is not `(5%2 = 1)`.

In [ ]:
def is_even(num):
  if num % 2 == 0:
    return True
  else:
    return False

#call the function
print(is_even(5))

#ask user for number
x = int(input("Please enter a number: "))
print(is_even(x))


False
Please enter a number: 4
True


**b)** **[10 pts]** Modify the `is_even` function you created in Q1.a to take a floating-point data as an input and return `True` if the ceiling of the input is Even. For example, `12.5` is not even, but `11.25` is even.

In [ ]:
#INSERT YOUR ANSWER HERE.
import math

def is_even(num):
  if math.ceil(num) % 2 == 0:
    return True
  else:
    return False


'''
#call the function
print(is_even(12.5))
'''


#ask user for number
x = float(input("Please enter a number: "))
print(is_even(x))


Please enter a number: 12.5
False


**c)** **[10 pts]** Define a function called `is_even_vec` that calls `isEven` function you updated in Q1.b to take a list of floating-point or integer numbers and return their results in a list.  For example, given `[1441.25, 231.5, 23]` the function returns `[True, True, False]`

In [ ]:
#define function is-even_vec
def is_even_vec():

  #ask user for input
  inp = input("Please enter the numbers with a comma seperating them: ")
  x = inp.split(",")

  lst_x = []
  num_lst = []
  for i in x:
    lst_x.append(float(i))

#call main function
  for i in lst_x:
    num_lst.append(is_even(i))        #call is_even function and print output

  return num_lst, lst_x




x = is_even_vec()
print(x [0])
  

Please enter the numbers with a comma seperating them: 1441.25,231.5,23
[True, True, False]


**d)** **[10 pts]** Define a function called `is_even_dict` that calls `is_even_vec` and returns the results in a dictionary with their corresponding input elements. \
For example, given `[1441.25, 231.5, 23]` the function returns `{1441.25: True, 231.5: True, 23: False}`

In [ ]:
#define function is_even_dict
def is_even_dict():
 
  x = is_even_vec()
  num_dict = dict()
  
  length = len(x[0])
  value = x[0]
  key = x[1]

  for i in range (0,length):
    num_dict[key[i]] = value[i]
  
  print(num_dict)

#Call function to run program
is_even_dict()

Please enter the numbers with a comma seperating them: 1441.25,231.5,23
{1441.25: True, 231.5: True, 23.0: False}


**e)** **[10 pts]** Define a function called `isEvenTuple` by modifying the function you created in Q1.d to traverse the values of the returned dictionary **in reverse order** and return the dictionary keys that has a **`TRUE`** value as a tuple.  For example, given `[1441.25, 231.5, 23]` the function returns `(231.5 1441.25)`.

In [ ]:
#Define function isEvenTuple
def isEvenTuple():

  x = is_even_vec()
  num_dict = dict()
  
  #reverse the orders of each list
  length = len(x[0])
  value = x[0]
  value = value[::-1]
  key = x[1]
  key = key[::-1]

  #create dictionary
  for i in range (0,length):
    num_dict[key[i]] = value[i]


  #use conditional statments to find all true values
  tup = []
  for j in num_dict.keys():
    if is_even(j) == True:
      tup.append(j)

  print(tuple(tup))

isEvenTuple()

Please enter the numbers with a comma seperating them: 1441.25,231.5,23
(231.5, 1441.25)


*****



### Question 2 **[30 pts]** :



**a) **[10 pts]** Define a function called `three_sub_str` that takes in as input a string and returns a string made of the first 3 and the last 3 characters from the input. If the string length is less than 3, return instead the string `Not Possible`.

Examples:
1. Input: 'watermelon'; Output: 'watlon
2. Input: 'try'; Output: 'trytry'
3. Input: 'as'; Output: Not Possible

In [ ]:
#define function three_sub_str
def three_sub_str():
  string = input("Please enter a string: ")

  f_str = []
  l_str = []
  #Use condition to check if string is long enough
  if len(string) < 3:
      print("Input: '", string, "'; Output: Not Possible")
  else:
      f_str = string[0:3]
      l_str = string[-3:]
      print("Input: '", string, "'; Output: '", f_str, l_str, "'" ,sep = '')
    

three_sub_str()


Please enter a string: watermelon
Input: 'watermelon'; Output: 'watlon'


**b)** **[10 pts]** Define a function `five_reverse` that takes as input a string and returns the reverse of the string if its length is a multiple of 5 else returns the original string.

Examples:
1. Input: 'GreenApple'; Output: 'elppAneerG'
2. Input 'RedApple'; Output 'RedApple'

In [ ]:
#define function five_reverse
def five_reverse():
  string = input("Please enter a string: ")

  #check if string is multiple of 5 or not
  if len(string) % 5 == 0:
    reverseString = string[::-1]
    print("Input: '", string, "'; Output: '", reverseString, "'")
  else:
    print("Input: '", string, "'; Output: '", string, "'")
  
five_reverse()

Please enter a string: Greenapple
Input: ' Greenapple '; Output: ' elppaneerG '


**c)** **[10 pts]** Define a function `count_char` that takes in as input a string and a boolen value and returns a dictonary that has each charater in the string as key and the count of the number of times the character appeared in the string as value. If the boolean value is `True` then it returns the dict with only the most frequent character else returns the entire dictonary

Examples:
1. Input: 'apple', False; Output: {'a': 1, 'p': 2, 'l': '1', e: '1'}
2. Input: 'apple', True; Output: {'p': 2}

In [ ]:
#define function count char
from ast import literal_eval
def count_char():
  boolean, string = (input('Enter Boolean expression: ')), input("Enter String: ")

  #create a dictionary
  char_dict = dict()
  max_char_dict = dict()

  for i in  string[0:len(string)]:
    count = string.count(i)
    char_dict[i] = count
    max_key = max(char_dict, key = char_dict.get)
  
  #Store values for maximum count only
  max_char_dict[max_key] = char_dict.get(max_key)
  
  #Use if condtion to run True or false bool
  if boolean == ("false") or boolean == "False":
    print("Input: '", string, "'", boolean, "; Output: ", char_dict)
  else:
    print("Input: '", string, "'", boolean, "; Output: ", max_char_dict)



count_char()

Enter Boolean expression: TRUE 
Enter String: applle
Input: ' applle ' TRUE  ; Output:  {'p': 2}


**BONUS** **[10 pts]** Define a function called `min_sub_str` that takes two string arguments ( S and T ) and returns the first possible substring (traversing from left) containing all the elements of `T`. For example: given `S = 'xBxxAxxCxxAxCxxBxxxAxCxBxxxAxxBxCx'` and `T = "ABC"`, returns **`"BxxAxxC"`**


In [96]:
#define function min-sub_str
import re
def min_sub_str():
  S, T = input("Please enter first string: "), input("Please enter second string: ")
  print(S)
  print(T)

  re_string = '.*'.join(T)
  REGEX = re.compile(re_string)
  print(REGEX.findall(S))



min_sub_str()

Please enter first string: 'xBxxAxxCxxAxCxxBxxxAxCxBxxxAxxBxCx'
Please enter second string: ABC
'xBxxAxxCxxAxCxxBxxxAxCxBxxxAxxBxCx'
ABC
['AxxCxxAxCxxBxxxAxCxBxxxAxxBxC']


*****

### Question 3 **[20 pts]**:


Define three classes, `Polygon`, `Rectangle` and `Square`. `Polygon` will be the parent class of `Triangle` and `Square`.

1. The `Polygon` should have a function called `WhoAmI` and it should print out `Triangle` if the current object is a triangle or `Square` if the current object is a square.

2. When you create a `Rectangle` object it should generate 2 random integers as the sides of the rectangle and store the values in the class.

3. Similarly, for `Square` it should randomly generate 1 random integer to denote one side of the square and store it in the class. 

4. Also, each of the `Rectangle` and `Square` classes should have a function called `findArea` that computes and returns the `Polygon` area. 

5. The `Polygon` should have a function called `side_lengths` to print the side lengths of the polygon.

6. The sides can be any value between 1 and 100, Inclusively.

Create 5 Triangle and 5 Square objects and print out all the properties in a loop.

It would be best if you mimicked this behaviour.

```
rect_obj = Rectangle()
sq_obj = Square()

rect_obj.WhoAmI()
Output "Rectangle"

rect_obj.side_lengths()
Output: [5,6] // Random integers that were chosen

rect_obj.findArea()
Output: 30

sq_obj.WhoAmI()
Output: "Square"

sq_obj.side_lengths()
Output: [6]

sq_obj.findArea()
Output: 36
```

In [95]:
import random
import math

#Define parent class polygon
class polygon:

  def __init__(self, no_unique_sides):
    self.no_unique_sides = no_unique_sides
    

  def who_am_i(self):
    print("The name of the polygon is {}".format(self.shape))
   

  def side_lengths(self):
    print("The side(s) of {} are {}".format(self.shape,self.sides))

  def findArea1(self, area):
    self.area = area
    print("The area of the {} is {}".format(self.shape, self.area))


#define sub class triangle
class triangle(polygon):
  pass

#define sub parent class rectangle
class rectangle(polygon):
 
  def __init__(self):
    self.shape = 'Rectangle'
    self.sides = rec_lst

  def findArea(self):
    rec_area = rec_lst[0] * rec_lst[1]
    self.findArea1(rec_area)


rec_lst = random.sample(range(0,100), 2)
  

#define sub class square
class square(rectangle):
  def __init__(self):
    self.shape = 'Square'
    self.sides = sqr_lst

  def findArea(self):
    sqr_area = sqr_lst ** 2
    self.findArea1(sqr_area)


sqr_lst = random.randint(0,100)

#define class for triangle
class triangle(polygon):

  def __init__(self):
    self.shape = 'Triangle'
    self.sides = tri_lst

  def findArea(self):
    p = (tri_lst[0] + tri_lst[1] + tri_lst[2]) / 2
    tri_area = math.sqrt(p * (p - tri_lst[0]) * (p - tri_lst[1]) * (p - tri_lst[2]))
    self.findArea1(round(tri_area, 2))

#* (p - tri_lst[1]) * (p - tri_lst[2])) ** 1/2
tri_lst = random.sample(range(0,100), 3)


#------------------------------------
#instantiate objects of each class
rect_obj = rectangle()
sq_obj = square()
tri_obj = triangle()




rect_obj.who_am_i()
rect_obj.side_lengths()
rect_obj.findArea()
print('-' * 50)


for i in range (0,5):
  sq_obj.who_am_i()
  sq_obj.side_lengths()
  sq_obj.findArea()
  print('-' * 50)
  tri_obj.who_am_i()
  tri_obj.side_lengths()
  tri_obj.findArea()
  print('-' * 50)
  print('-' * 50)


The name of the polygon is Rectangle
The side(s) of Rectangle are [89, 11]
The area of the Rectangle is 979
--------------------------------------------------
The name of the polygon is Square
The side(s) of Square are 26
The area of the Square is 676
--------------------------------------------------
The name of the polygon is Triangle
The side(s) of Triangle are [72, 70, 9]
The area of the Triangle is 310.88
--------------------------------------------------
--------------------------------------------------
The name of the polygon is Square
The side(s) of Square are 26
The area of the Square is 676
--------------------------------------------------
The name of the polygon is Triangle
The side(s) of Triangle are [72, 70, 9]
The area of the Triangle is 310.88
--------------------------------------------------
--------------------------------------------------
The name of the polygon is Square
The side(s) of Square are 26
The area of the Square is 676
----------------------------------

#### This is the end of assignment 2